# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-29 17:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_pool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assunto',
            name='ticket_associado',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
