# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-29 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_pool', '0004_entrada_ticket_associado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='ticket_associado',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
