# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-12 15:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('knowledge_pool', '0005_auto_20170729_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='dono',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
