# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-01 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_pool', '0008_auto_20171025_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
