# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-04 17:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_pool', '0009_entrada_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrada',
            old_name='like',
            new_name='qtd_utilizacoes',
        ),
    ]
